### ISSUE TITLE
1.2.76 버전에서 레이아웃 배치가 잘못됨 / Version 1.2.76 has broken layout.

### ISSUE THREAD

**Issue by leesu1234** [DuelitDev/PapersPleaseDPRK#3]
![image](https://github.com/DuelitDev/PapersPleaseDPRK/assets/141801578/333a3b98-24ab-4a87-823a-776a76acc9ba)
사진을 이렇게 올리는게 맞나 모르겠네요... 깃허브를 처음 써봐서 아무튼 assets 파일과 loc 파일의 위치가 바뀌었는지 E:\steam\steamapps\common\PapersPlease 이경로로 가면 덮어 씌울 assets 파일과 loc 파일이 보이지 않네요

**Comment by leesu1234** [comment]
> ![image](https://user-images.githubusercontent.com/141801578/259295352-333a3b98-24ab-4a87-823a-776a76acc9ba.png) 사진을 이렇게 올리는게 맞나 모르겠네요... 깃허브를 처음 써봐서 아무튼 assets 파일과 loc 파일의 위치가 바뀌었는지 E:\steam\steamapps\common\PapersPlease 이경로로 가면 덮어 씌울 assets 파일과 loc 파일이 보이지 않네요

글 수정 합니다! 스팀 베타에서 32비트로 바꿔서 플레이하고 있습니다! 만들어주셔서 감사합니다!

**Comment by leesu1234** [comment]
![image](https://github.com/DuelitDev/PapersPleaseDPRK/assets/141801578/2e587d50-ed5f-423d-8c13-27f878841b56)
이오류가 뜨면서 게임이 꺼지네요 ㅠㅠㅠ

**Comment by DuelitDev** [comment]
#1에 관해서: 업데이트로 인해 기존 패치가 적용이 되지 않은 점은 인지하고 있고, 현재는 리버싱 시도 중입니다. 요즘 바쁜 관계로 못 건드린 점도 있고요. 아마 10월 내로는 하지 않을까 생각합니다.

#3에 관해서: 아마 다시 한 번 패치를 하시면 해결될 것 같습니다.

**Comment by DuelitDev** [comment]
#3 추가: 직접 확인해봤는데 아마 `legacy - Legacy 32-bit build (1.1.65)` 버전을 선택하신 게 아닌가 싶습니다.
`legacy-64 - Legacy 64-bit build (1.2.76)` 버전을 선택하셔야 플레이 하실 수 있습니다.

**Comment by leesu1234** [comment]
아ㅠㅠㅠㅠ 지금이라도 즐겁게 친구와 즐겨봅니다... 감사합니다!!!

**Comment by leesu1234** [comment]
근데 심사대랑 지도 버튼이 좀 밀려서 심사대가 이상하게 보이고 지도 버튼 클릭을 못하는데 이건 어떻게 해결해야하나요...?

**Comment by DuelitDev** [comment]
> 지도

사진 첨부가 가능할까요?

**Comment by leesu1234** [comment]
![화면 캡처 2023-12-04 201621](https://github.com/DuelitDev/PapersPleaseDPRK/assets/141801578/954022fc-c083-4ace-9520-6350b3c561fa)
![화면 캡처 2023-12-04 201757](https://github.com/DuelitDev/PapersPleaseDPRK/assets/141801578/fb9ee41f-8ad5-47b1-b08c-4bda9a35d34a)
첫번째 사진이 검문소 사진이고 두번째 사진에 빨간색 동그라미가 중국인데 저걸 클릭하면 중국이 열리더라고요! 다른건 모르겠는데 이 두가지가 밀려있었습니다 ㅠㅠ

**Comment by VaughanDrix1960** [comment]
저도 완전히 같은 증상이네요... 해결 방법 찾으려고 한참 검색했는데 마땅한 게 없는거 같습니다. 혹여나 바쁘시지 않다면 이 패치 버그 해결을 도와주시면 감사하겠습니다 ㅠㅠ

**Comment by leesu1234** [comment]
저도 기다리는중입니다 ㅠㅠㅠㅠ

**Comment by DuelitDev** [comment]
중간고사 끝나고 고쳐보겠습니다. @leesu1234 @VaughanDrix1960

**Comment by leesu1234** [comment]
감사합니다 제작자님!

**Comment by DuelitDev** [comment]
@leesu1234 @VaughanDrix1960 1.3.1276 베타 올렸습니다. 아직 제가 확인을 못해서 문제 없는지 테스트 해주시면 감사하겠습니다!

**Comment by leesu1234** [comment]
넵 감사합니다 선생님 ㅠㅠㅠ

**Comment by leesu1234** [comment]
![화면 캡처 2024-10-26 013529](https://github.com/user-attachments/assets/51bd1c80-3dd7-454b-aa3b-e5b34e7a880d)
검문소는 고쳐졌습니다!

**Comment by DuelitDev** [comment]
@leesu1234 
국가명의 위치가 잘못 배치되어 확인하기 어렵다는 문제가 있으시다는 거죠?
아마도 제가 1.1.65에서 1.2.76으로 마이그레이션 하면서 설정 파일을 덮어씌웠었는데 원작은 설정이 수정되어 있었나 봅니다.
관련된 부분을 찾아 수정해보겠습니다!

**Comment by DuelitDev** [comment]
@leesu1234 
수정 완료 되었습니다.

**Comment by leesu1234** [comment]
감사합니다! ㅠㅠㅠㅠ 재미있게 잘 플레이하도록 하겠습니다!
