### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by BritishCat105** [DuelitDev/PapersPleaseDPRK#4]
저도 asset 이슈창 뜨면서 꺼지길래 한번 더 다운해서 덮어써봤는데 안됩니다... 방도가 있을까요?

**Comment by DuelitDev** [comment]
직접 확인해봤는데 아마 `legacy - Legacy 32-bit build (1.1.65)` 버전을 선택하신 게 아닌가 싶습니다.
`legacy-64 - Legacy 64-bit build (1.2.76)` 버전을 선택하셔야 플레이 하실 수 있습니다.
