### ISSUE TITLE
레이아웃 배치 문제는 해결 됐습니다 근데 튕김 문제가 있습니다..

### ISSUE THREAD

**Issue by leesu1234** [DuelitDev/PapersPleaseDPRK#5]
어떤오류창도 없이 특정 인물이 들어오면 누구인지도 안보이고 바로 게임이 꺼져버립니다.. 여러번 해본 결과 1일차 1~5번째 사람 사이에서 계속 튕깁니다 2일차도 마찬가지 입니다

**Comment by DuelitDev** [comment]
@leesu1234 
모드 패키징 툴의 버그로 인한 오류였습니다. 

'병팔-김'(원작에서 'Simon Wens'로 30일 차에 등장)의 UTF-8 인코딩이 오류를 발생시키는 지는 아직 확인하지 못했습니다. 

모드 패키징 툴의 버그만 해결한 버전인 `1.5.1276b1`와, UTF-8 인코딩 적용 및 기타 에셋 개선이 이루어진 `1.5.1276b2`로 업로드 하도록 하겠습니다. 

테스트 후 1.5.1276 stable 릴리즈를 배포할 예정입니다.

**Comment by leesu1234** [comment]
감사합니당
